import type { Rng } from '../game/rng.js';

/**
 * Guest identity (docs/logic/profile-and-identity.md): a new account gets a random nickname and avatar from curated
 * preset lists, never free text. The avatar keys match the 24 faces of the design kit (`avatar-01` .. `avatar-24`).
 */
export const AVATAR_KEYS: readonly string[] = Array.from({ length: 24 }, (_, i) => `avatar-${String(i + 1).padStart(2, '0')}`);

export const NICKNAMES: readonly string[] = [
  'دوزاری‌باز', 'سکه‌طلا', 'شاهی‌خان', 'پول‌سیاه', 'ریال‌آقا', 'تومن‌بانو', 'هزارتومنی', 'قِران‌دار',
  'بستنی‌چی', 'پفک‌نمکی', 'آدامس‌بادی', 'نوستالژی', 'کاست‌باز', 'ویدیوکلوپی', 'تلفن‌سکه‌ای', 'ماشین‌پیکان',
  'قند‌پهلو', 'چای‌دبش', 'نون‌سنگک', 'کولر‌آبی', 'رادیو‌ترانزیستور', 'تلویزیون‌سیاه‌سفید', 'مدادتراش', 'خودکارکیلو',
  'جوجه‌طلا', 'کوچولوی‌پیر', 'دوزاری‌کج', 'سکه‌پرون', 'ستاره‌دنباله‌دار', 'قهرمان‌محل', 'کاکتوس', 'گربه‌ملوس',
  'پلنگ‌صورتی', 'خرس‌قطبی', 'زرافه‌خنده', 'جغد‌شب', 'روباه‌حیله', 'لاک‌پشت‌تند', 'پنگوئن‌خانگی', 'شاهزاده‌نان',
];

export interface GuestIdentity {
  nickname: string;
  avatarKey: string;
}

/** Picks a random nickname and avatar. The rng is injected so tests are deterministic. */
export function randomGuestIdentity(rng: Rng): GuestIdentity {
  const pick = <T>(items: readonly T[]): T => items[Math.floor(rng() * items.length)] as T;
  return { nickname: pick(NICKNAMES), avatarKey: pick(AVATAR_KEYS) };
}

/** Device ids are generated by the client (a UUID kept in secure storage); we only check the shape. */
export const DEVICE_ID_PATTERN = /^[A-Za-z0-9_-]{16,64}$/;
