/** Icon pack categories with Persian names (designs 12 and 14). GENERATED by scripts/gen-items.mjs, do not edit. */
export interface ItemGroup {
  id: string;
  titleFa: string;
  color: string;
  icons: { key: string; fa: string }[];
}
export const ITEM_GROUPS: readonly ItemGroup[] = [
 {
  "id": "item-0",
  "titleFa": "پول و گنجینه",
  "color": "#FFC93C",
  "icons": [
   {
    "key": "coin",
    "fa": "سکهٔ دوزاری"
   },
   {
    "key": "coinStack",
    "fa": "کپهٔ سکه"
   },
   {
    "key": "coinBag",
    "fa": "کیسهٔ سکه"
   },
   {
    "key": "chest",
    "fa": "صندوقچه"
   },
   {
    "key": "gem",
    "fa": "جواهر"
   },
   {
    "key": "piggy",
    "fa": "قلک"
   },
   {
    "key": "banknote",
    "fa": "اسکناس"
   },
   {
    "key": "goldBar",
    "fa": "شمش طلا"
   }
  ]
 },
 {
  "id": "item-1",
  "titleFa": "کمک‌ها و قدرت‌ها",
  "color": "#3FC1F0",
  "icons": [
   {
    "key": "lantern",
    "fa": "فانوس راهنما"
   },
   {
    "key": "magnifier",
    "fa": "ذره‌بین"
   },
   {
    "key": "hourglass",
    "fa": "ساعت شنی"
   },
   {
    "key": "dice",
    "fa": "تاس بُر"
   },
   {
    "key": "heart",
    "fa": "جان اضافه"
   },
   {
    "key": "freeze",
    "fa": "یخ‌زدن زمان"
   },
   {
    "key": "scissors",
    "fa": "حذف یک کلمه"
   },
   {
    "key": "eraser",
    "fa": "پاک‌کن"
   },
   {
    "key": "magicLamp",
    "fa": "چراغ جادو"
   },
   {
    "key": "key",
    "fa": "کلید"
   },
   {
    "key": "lock",
    "fa": "قفل"
   }
  ]
 },
 {
  "id": "item-2",
  "titleFa": "اجناس بازار",
  "color": "#E8743B",
  "icons": [
   {
    "key": "teaGlass",
    "fa": "استکان چای"
   },
   {
    "key": "teapot",
    "fa": "قوری"
   },
   {
    "key": "samovar",
    "fa": "سماور"
   },
   {
    "key": "pomegranate",
    "fa": "انار"
   },
   {
    "key": "watermelon",
    "fa": "هندوانه"
   },
   {
    "key": "saffron",
    "fa": "زعفران"
   },
   {
    "key": "pistachio",
    "fa": "پسته"
   },
   {
    "key": "rug",
    "fa": "فرش"
   },
   {
    "key": "spiceSack",
    "fa": "کیسهٔ ادویه"
   },
   {
    "key": "jug",
    "fa": "کوزه"
   },
   {
    "key": "bread",
    "fa": "نان"
   },
   {
    "key": "pashmak",
    "fa": "پشمک"
   },
   {
    "key": "sohan",
    "fa": "سوهان"
   }
  ]
 },
 {
  "id": "item-3",
  "titleFa": "جایزه و افتخار",
  "color": "#FF4D8D",
  "icons": [
   {
    "key": "crown",
    "fa": "تاج"
   },
   {
    "key": "trophy",
    "fa": "جام"
   },
   {
    "key": "medal",
    "fa": "مدال"
   },
   {
    "key": "star",
    "fa": "ستاره"
   },
   {
    "key": "ticket",
    "fa": "بلیت تورنومنت"
   },
   {
    "key": "gift",
    "fa": "کادو"
   },
   {
    "key": "envelope",
    "fa": "نامه"
   },
   {
    "key": "scroll",
    "fa": "طومار"
   },
   {
    "key": "flag",
    "fa": "پرچم"
   },
   {
    "key": "balloons",
    "fa": "بادکنک"
   },
   {
    "key": "rosette",
    "fa": "نشان"
   },
   {
    "key": "fireworks",
    "fa": "آتش‌بازی"
   }
  ]
 },
 {
  "id": "item-4",
  "titleFa": "انرژی و زمان",
  "color": "#7ED957",
  "icons": [
   {
    "key": "potion",
    "fa": "معجون انرژی"
   },
   {
    "key": "xpPotion",
    "fa": "معجون تجربه"
   },
   {
    "key": "bolt",
    "fa": "صاعقه"
   },
   {
    "key": "calendar",
    "fa": "تقویم"
   },
   {
    "key": "alarm",
    "fa": "ساعت زنگی"
   },
   {
    "key": "map",
    "fa": "نقشه"
   },
   {
    "key": "compass",
    "fa": "قطب‌نما"
   }
  ]
 },
 {
  "id": "item-5",
  "titleFa": "نوستالژی",
  "color": "#A66BF0",
  "icons": [
   {
    "key": "cassette",
    "fa": "نوار کاست"
   },
   {
    "key": "radio",
    "fa": "رادیو"
   },
   {
    "key": "phone",
    "fa": "تلفن قدیمی"
   },
   {
    "key": "marbles",
    "fa": "تیله"
   },
   {
    "key": "top",
    "fa": "فرفره"
   },
   {
    "key": "kite",
    "fa": "بادبادک"
   }
  ]
 },
 {
  "id": "product-6",
  "titleFa": "میوه",
  "color": "#FF8FB6",
  "icons": [
   {
    "key": "apple",
    "fa": "سیب"
   },
   {
    "key": "pear",
    "fa": "گلابی"
   },
   {
    "key": "grape",
    "fa": "انگور"
   },
   {
    "key": "cherry",
    "fa": "گیلاس"
   },
   {
    "key": "strawberry",
    "fa": "توت‌فرنگی"
   },
   {
    "key": "orange",
    "fa": "پرتقال"
   },
   {
    "key": "lemon",
    "fa": "لیمو"
   },
   {
    "key": "banana",
    "fa": "موز"
   },
   {
    "key": "peach",
    "fa": "هلو"
   },
   {
    "key": "fig",
    "fa": "انجیر"
   },
   {
    "key": "dates",
    "fa": "خرما"
   }
  ]
 },
 {
  "id": "product-7",
  "titleFa": "آجیل و سبزیجات",
  "color": "#B8F08F",
  "icons": [
   {
    "key": "walnut",
    "fa": "گردو"
   },
   {
    "key": "almond",
    "fa": "بادام"
   },
   {
    "key": "tomato",
    "fa": "گوجه"
   },
   {
    "key": "cucumber",
    "fa": "خیار"
   },
   {
    "key": "carrot",
    "fa": "هویج"
   },
   {
    "key": "eggplant",
    "fa": "بادمجان"
   },
   {
    "key": "pepper",
    "fa": "فلفل"
   },
   {
    "key": "onion",
    "fa": "پیاز"
   },
   {
    "key": "potato",
    "fa": "سیب‌زمینی"
   },
   {
    "key": "garlic",
    "fa": "سیر"
   },
   {
    "key": "mushroom",
    "fa": "قارچ"
   },
   {
    "key": "corn",
    "fa": "ذرت"
   }
  ]
 },
 {
  "id": "product-8",
  "titleFa": "بقالی",
  "color": "#FFE48A",
  "icons": [
   {
    "key": "cheese",
    "fa": "پنیر"
   },
   {
    "key": "egg",
    "fa": "تخم‌مرغ"
   },
   {
    "key": "milk",
    "fa": "شیر"
   },
   {
    "key": "honey",
    "fa": "عسل"
   },
   {
    "key": "jam",
    "fa": "مربا"
   },
   {
    "key": "pickles",
    "fa": "ترشی"
   },
   {
    "key": "oil",
    "fa": "روغن"
   },
   {
    "key": "rice",
    "fa": "برنج"
   },
   {
    "key": "flour",
    "fa": "آرد"
   },
   {
    "key": "sugar",
    "fa": "قند"
   },
   {
    "key": "salt",
    "fa": "نمک"
   },
   {
    "key": "tea",
    "fa": "چای"
   },
   {
    "key": "spices",
    "fa": "ادویه"
   },
   {
    "key": "cinnamon",
    "fa": "دارچین"
   },
   {
    "key": "cardamom",
    "fa": "هل"
   }
  ]
 },
 {
  "id": "product-9",
  "titleFa": "نون و شیرینی",
  "color": "#FFAA7A",
  "icons": [
   {
    "key": "bread2",
    "fa": "نان باگت"
   },
   {
    "key": "sangak",
    "fa": "سنگک"
   },
   {
    "key": "cookie",
    "fa": "کلوچه"
   },
   {
    "key": "cake",
    "fa": "کیک"
   },
   {
    "key": "icecream",
    "fa": "بستنی"
   },
   {
    "key": "lollipop",
    "fa": "آبنبات چوبی"
   },
   {
    "key": "candy",
    "fa": "آبنبات"
   },
   {
    "key": "gaz",
    "fa": "گز"
   },
   {
    "key": "baklava",
    "fa": "باقلوا"
   }
  ]
 },
 {
  "id": "product-10",
  "titleFa": "غذا و نوشیدنی",
  "color": "#8FDCFA",
  "icons": [
   {
    "key": "kebab",
    "fa": "کباب"
   },
   {
    "key": "pizza",
    "fa": "پیتزا"
   },
   {
    "key": "burger",
    "fa": "همبرگر"
   },
   {
    "key": "fish",
    "fa": "ماهی"
   },
   {
    "key": "chicken",
    "fa": "مرغ"
   },
   {
    "key": "coffee",
    "fa": "قهوه"
   },
   {
    "key": "juice",
    "fa": "آبمیوه"
   },
   {
    "key": "soda",
    "fa": "نوشابه"
   },
   {
    "key": "water",
    "fa": "آب"
   }
  ]
 },
 {
  "id": "product-11",
  "titleFa": "خونه و آشپزخونه",
  "color": "#C9A3FF",
  "icons": [
   {
    "key": "carpet",
    "fa": "فرش"
   },
   {
    "key": "vase",
    "fa": "گلدان"
   },
   {
    "key": "lamp",
    "fa": "چراغ"
   },
   {
    "key": "candle",
    "fa": "شمع"
   },
   {
    "key": "mirror",
    "fa": "آینه"
   },
   {
    "key": "clock",
    "fa": "ساعت"
   },
   {
    "key": "pot",
    "fa": "قابلمه"
   },
   {
    "key": "pan",
    "fa": "ماهیتابه"
   },
   {
    "key": "knife",
    "fa": "چاقو"
   },
   {
    "key": "spoon",
    "fa": "قاشق"
   },
   {
    "key": "plate",
    "fa": "بشقاب"
   },
   {
    "key": "broom",
    "fa": "جارو"
   },
   {
    "key": "bucket",
    "fa": "سطل"
   },
   {
    "key": "basket",
    "fa": "سبد"
   },
   {
    "key": "scale",
    "fa": "ترازو"
   }
  ]
 },
 {
  "id": "product-12",
  "titleFa": "پوشاک و زیورآلات",
  "color": "#FF8FB6",
  "icons": [
   {
    "key": "hat",
    "fa": "کلاه"
   },
   {
    "key": "shoe",
    "fa": "کفش"
   },
   {
    "key": "shirt",
    "fa": "پیراهن"
   },
   {
    "key": "dress",
    "fa": "لباس"
   },
   {
    "key": "scarf",
    "fa": "شال"
   },
   {
    "key": "umbrella",
    "fa": "چتر"
   },
   {
    "key": "bag",
    "fa": "کیف"
   },
   {
    "key": "ring",
    "fa": "انگشتر"
   },
   {
    "key": "necklace",
    "fa": "گردنبند"
   },
   {
    "key": "bracelet",
    "fa": "دستبند"
   },
   {
    "key": "perfume",
    "fa": "عطر"
   },
   {
    "key": "lipstick",
    "fa": "رژ لب"
   },
   {
    "key": "comb",
    "fa": "شانه"
   },
   {
    "key": "soap",
    "fa": "صابون"
   },
   {
    "key": "toothbrush",
    "fa": "مسواک"
   }
  ]
 },
 {
  "id": "product-13",
  "titleFa": "سرگرمی و گل",
  "color": "#B8F08F",
  "icons": [
   {
    "key": "book",
    "fa": "کتاب"
   },
   {
    "key": "pencil",
    "fa": "مداد"
   },
   {
    "key": "camera",
    "fa": "دوربین"
   },
   {
    "key": "headphones",
    "fa": "هدفون"
   },
   {
    "key": "ball",
    "fa": "توپ"
   },
   {
    "key": "teddy",
    "fa": "عروسک"
   },
   {
    "key": "guitar",
    "fa": "گیتار"
   },
   {
    "key": "tar",
    "fa": "تار"
   },
   {
    "key": "daf",
    "fa": "دف"
   },
   {
    "key": "rose",
    "fa": "گل رز"
   },
   {
    "key": "tulip",
    "fa": "لاله"
   },
   {
    "key": "sunflower",
    "fa": "آفتابگردان"
   },
   {
    "key": "cactus",
    "fa": "کاکتوس"
   },
   {
    "key": "cart",
    "fa": "چرخ خرید"
   }
  ]
 },
 {
  "id": "sample-14",
  "titleFa": "نان و بقالی",
  "color": "#FFE48A",
  "icons": [
   {
    "key": "peykanJ",
    "fa": "پیکان جوانان"
   },
   {
    "key": "barbari",
    "fa": "نان بربری"
   },
   {
    "key": "lavash",
    "fa": "نان لواش"
   },
   {
    "key": "taftoon",
    "fa": "نان تافتون"
   },
   {
    "key": "yogurt",
    "fa": "ماست"
   },
   {
    "key": "meat",
    "fa": "گوشت گوسفندی"
   },
   {
    "key": "halvaArde",
    "fa": "حلوا ارده"
   }
  ]
 },
 {
  "id": "sample-15",
  "titleFa": "تنقلات",
  "color": "#FF8FB6",
  "icons": [
   {
    "key": "pofak",
    "fa": "پفک نمکی"
   },
   {
    "key": "chips",
    "fa": "چیپس"
   },
   {
    "key": "gum",
    "fa": "آدامس"
   },
   {
    "key": "chocolate",
    "fa": "شکلات تکی"
   },
   {
    "key": "gummy",
    "fa": "پاستیل"
   },
   {
    "key": "nokhodchi",
    "fa": "نخودچی کشمش"
   },
   {
    "key": "ajil",
    "fa": "آجیل مخلوط"
   },
   {
    "key": "bastaniSonati",
    "fa": "بستنی سنتی"
   },
   {
    "key": "zoolbia",
    "fa": "زولبیا بامیه"
   }
  ]
 },
 {
  "id": "sample-16",
  "titleFa": "نوشیدنی",
  "color": "#8FDCFA",
  "icons": [
   {
    "key": "doogh",
    "fa": "دوغ"
   },
   {
    "key": "sharbat",
    "fa": "شربت آلبالو"
   },
   {
    "key": "araq",
    "fa": "عرق نعنا"
   }
  ]
 },
 {
  "id": "sample-17",
  "titleFa": "غذا",
  "color": "#FFAA7A",
  "icons": [
   {
    "key": "falafel",
    "fa": "ساندویچ فلافل"
   },
   {
    "key": "dizi",
    "fa": "دیزی سنگی"
   },
   {
    "key": "ash",
    "fa": "آش رشته"
   },
   {
    "key": "halim",
    "fa": "حلیم"
   },
   {
    "key": "sandwich",
    "fa": "ساندویچ کالباس"
   }
  ]
 },
 {
  "id": "sample-18",
  "titleFa": "حمل‌ونقل",
  "color": "#B8F08F",
  "icons": [
   {
    "key": "busTicket",
    "fa": "بلیت اتوبوس شهری"
   },
   {
    "key": "metroTicket",
    "fa": "بلیت مترو"
   },
   {
    "key": "taxi",
    "fa": "کرایه‌ی تاکسی"
   },
   {
    "key": "gasPump",
    "fa": "بنزین"
   },
   {
    "key": "cng",
    "fa": "گاز CNG"
   },
   {
    "key": "bus",
    "fa": "اتوبوس تهران–شیراز"
   },
   {
    "key": "train",
    "fa": "قطار تهران–مشهد"
   },
   {
    "key": "peykan",
    "fa": "پیکان"
   },
   {
    "key": "vanet",
    "fa": "پیکان وانت"
   },
   {
    "key": "pride",
    "fa": "پراید"
   },
   {
    "key": "samand",
    "fa": "سمند"
   },
   {
    "key": "p206",
    "fa": "پژو ۲۰۶"
   },
   {
    "key": "motorbike",
    "fa": "موتور هندا ۱۲۵"
   },
   {
    "key": "bicycle",
    "fa": "دوچرخه"
   }
  ]
 },
 {
  "id": "sample-19",
  "titleFa": "لوازم برقی و سرگرمی",
  "color": "#C9A3FF",
  "icons": [
   {
    "key": "tv",
    "fa": "تلویزیون ۲۱ اینچ"
   },
   {
    "key": "nokia",
    "fa": "نوکیا ۱۱۰۰"
   },
   {
    "key": "cd",
    "fa": "سی‌دی بازی"
   },
   {
    "key": "flash",
    "fa": "فلش ۴ گیگ"
   },
   {
    "key": "atari",
    "fa": "آتاری"
   },
   {
    "key": "handheld",
    "fa": "بازی‌ماشین"
   },
   {
    "key": "fridge",
    "fa": "یخچال ساید"
   },
   {
    "key": "washer",
    "fa": "لباس‌شویی"
   },
   {
    "key": "filmRoll",
    "fa": "فیلم عکاسی"
   },
   {
    "key": "newspaper",
    "fa": "روزنامه"
   },
   {
    "key": "magazine",
    "fa": "مجله‌ی کودک"
   },
   {
    "key": "gamenet",
    "fa": "گیم‌نت"
   },
   {
    "key": "vhs",
    "fa": "فیلم ویدیو"
   }
  ]
 },
 {
  "id": "sample-20",
  "titleFa": "اسباب‌بازی",
  "color": "#FFE48A",
  "icons": [
   {
    "key": "domino",
    "fa": "دومینو"
   },
   {
    "key": "beachBall",
    "fa": "توپ پلاستیکی"
   },
   {
    "key": "football",
    "fa": "توپ چرمی"
   }
  ]
 },
 {
  "id": "sample-21",
  "titleFa": "نوشت‌افزار",
  "color": "#8FDCFA",
  "icons": [
   {
    "key": "notebook",
    "fa": "دفتر ۴۰ برگ"
   },
   {
    "key": "pen",
    "fa": "خودکار بیک"
   },
   {
    "key": "testBook",
    "fa": "کتاب تست"
   },
   {
    "key": "ruler",
    "fa": "خط‌کش"
   },
   {
    "key": "storybook",
    "fa": "کتاب قصه"
   }
  ]
 },
 {
  "id": "sample-22",
  "titleFa": "پوشاک و بهداشت",
  "color": "#FF8FB6",
  "icons": [
   {
    "key": "sock",
    "fa": "جوراب نخی"
   },
   {
    "key": "beanie",
    "fa": "کلاه نخی"
   },
   {
    "key": "jeans",
    "fa": "شلوار جین"
   },
   {
    "key": "toothpaste",
    "fa": "خمیردندان"
   },
   {
    "key": "shampoo",
    "fa": "شامپو بچه"
   },
   {
    "key": "tissue",
    "fa": "دستمال کاغذی"
   },
   {
    "key": "diaper",
    "fa": "پوشک بچه"
   }
  ]
 },
 {
  "id": "sample-23",
  "titleFa": "خدمات، خانه و پول",
  "color": "#B8F08F",
  "icons": [
   {
    "key": "barber",
    "fa": "آرایشگاه"
   },
   {
    "key": "photoId",
    "fa": "عکس ۳×۴"
   },
   {
    "key": "apartment",
    "fa": "اجاره‌ی ماهانه"
   },
   {
    "key": "house",
    "fa": "متر خانه"
   },
   {
    "key": "bill",
    "fa": "قبض گاز"
   },
   {
    "key": "payphone",
    "fa": "تلفن سکه‌ای"
   },
   {
    "key": "pump",
    "fa": "پمپ دوچرخه"
   },
   {
    "key": "bulb",
    "fa": "لامپ رشته‌ای"
   },
   {
    "key": "battery",
    "fa": "باتری قلمی"
   },
   {
    "key": "postcard",
    "fa": "کارت پستال"
   },
   {
    "key": "lighter",
    "fa": "فندک"
   },
   {
    "key": "goldCoin",
    "fa": "سکه بهار آزادی"
   },
   {
    "key": "dollar",
    "fa": "دلار"
   }
  ]
 }
];
