/**
 * Starting list of cities; the admin panel can add, rename and hide cities (table `cities`). Slugs are stable keys.
 * `province` keys `PROVINCES` (D101): Iranian cities point at their province, abroad cities at their own entry,
 * «شهر دیگر» at none. Missing defaults are added to an existing table at startup, in this order.
 */
export const DEFAULT_CITIES: readonly { slug: string; nameFa: string; province: string | null }[] = [
  { slug: 'tehran', nameFa: 'تهران', province: 'tehran' },
  { slug: 'mashhad', nameFa: 'مشهد', province: 'khrazavi' },
  { slug: 'isfahan', nameFa: 'اصفهان', province: 'isfahan' },
  { slug: 'karaj', nameFa: 'کرج', province: 'alborz' },
  { slug: 'shiraz', nameFa: 'شیراز', province: 'fars' },
  { slug: 'tabriz', nameFa: 'تبریز', province: 'azsharghi' },
  { slug: 'qom', nameFa: 'قم', province: 'qom' },
  { slug: 'ahvaz', nameFa: 'اهواز', province: 'khuzestan' },
  { slug: 'kermanshah', nameFa: 'کرمانشاه', province: 'kermanshah' },
  { slug: 'urmia', nameFa: 'ارومیه', province: 'azgharbi' },
  { slug: 'rasht', nameFa: 'رشت', province: 'gilan' },
  { slug: 'zahedan', nameFa: 'زاهدان', province: 'sistan' },
  { slug: 'hamadan', nameFa: 'همدان', province: 'hamadan' },
  { slug: 'kerman', nameFa: 'کرمان', province: 'kerman' },
  { slug: 'yazd', nameFa: 'یزد', province: 'yazd' },
  { slug: 'ardabil', nameFa: 'اردبیل', province: 'ardabil' },
  { slug: 'bandar-abbas', nameFa: 'بندرعباس', province: 'hormozgan' },
  { slug: 'arak', nameFa: 'اراک', province: 'markazi' },
  { slug: 'zanjan', nameFa: 'زنجان', province: 'zanjan' },
  { slug: 'sanandaj', nameFa: 'سنندج', province: 'kurdistan' },
  { slug: 'qazvin', nameFa: 'قزوین', province: 'qazvin' },
  { slug: 'khorramabad', nameFa: 'خرم‌آباد', province: 'lorestan' },
  { slug: 'gorgan', nameFa: 'گرگان', province: 'golestan' },
  { slug: 'sari', nameFa: 'ساری', province: 'mazandaran' },
  { slug: 'bushehr', nameFa: 'بوشهر', province: 'bushehr' },
  { slug: 'birjand', nameFa: 'بیرجند', province: 'khjonubi' },
  { slug: 'bojnord', nameFa: 'بجنورد', province: 'khshomali' },
  { slug: 'semnan', nameFa: 'سمنان', province: 'semnan' },
  { slug: 'ilam', nameFa: 'ایلام', province: 'ilam' },
  { slug: 'yasuj', nameFa: 'یاسوج', province: 'kohgiluyeh' },
  { slug: 'shahrekord', nameFa: 'شهرکرد', province: 'chaharmahal' },
  { slug: 'abadan', nameFa: 'آبادان', province: 'khuzestan' },
  { slug: 'dezful', nameFa: 'دزفول', province: 'khuzestan' },
  { slug: 'kish', nameFa: 'کیش', province: 'hormozgan' },
  { slug: 'other', nameFa: 'شهر دیگر', province: null },
  { slug: 'istanbul', nameFa: 'استانبول', province: 'istanbul' },
  { slug: 'dubai', nameFa: 'دبی', province: 'dubai' },
  { slug: 'toronto', nameFa: 'تورنتو', province: 'toronto' },
  { slug: 'los-angeles', nameFa: 'لس‌آنجلس', province: 'la' },
  { slug: 'london', nameFa: 'لندن', province: 'london' },
  { slug: 'paris', nameFa: 'پاریس', province: 'paris' },
  { slug: 'berlin', nameFa: 'برلین', province: 'berlin' },
  { slug: 'abroad-other', nameFa: 'کشور دیگر', province: 'abroad' },
];
