/**
 * Starting list of cities; the admin panel can add, rename and hide cities (table `cities`). Slugs are stable keys.
 * `province` keys `PROVINCES` (D101): Iranian cities point at their province, abroad cities at their own entry,
 * «شهر دیگر» at none. Each has a default slogan (D205) the admin can rewrite. Missing defaults are added to an existing table at startup, in this order.
 */
export const DEFAULT_CITIES: readonly { slug: string; nameFa: string; province: string | null; sloganFa: string }[] = [
  { slug: 'tehran', nameFa: 'تهران', province: 'tehran', sloganFa: 'تهران، جایی که همه‌چیز گرون‌تر از دیروزه!' },
  { slug: 'mashhad', nameFa: 'مشهد', province: 'khrazavi', sloganFa: 'یه زیارت، یه زعفرون، یه عالمه خاطره!' },
  { slug: 'isfahan', nameFa: 'اصفهان', province: 'isfahan', sloganFa: 'اصفهان نصف جهان، قیمت‌اش هم نصف نمی‌شه!' },
  { slug: 'karaj', nameFa: 'کرج', province: 'alborz', sloganFa: 'کرج، از ترافیک جاده تا دل بازیکن‌ها!' },
  { slug: 'shiraz', nameFa: 'شیراز', province: 'fars', sloganFa: 'شیراز، شهر شعر و دوزاریِ قدیم!' },
  { slug: 'tabriz', nameFa: 'تبریز', province: 'azsharghi', sloganFa: 'تبریز، قیمتا رو بازار بهتر می‌دونه!' },
  { slug: 'qom', nameFa: 'قم', province: 'qom', sloganFa: 'قم، سوهانش شیرین‌تر از برد دوئل!' },
  { slug: 'ahvaz', nameFa: 'اهواز', province: 'khuzestan', sloganFa: 'اهواز، داغ‌تر از قیمت‌ها تو تابستون!' },
  { slug: 'kermanshah', nameFa: 'کرمانشاه', province: 'kermanshah', sloganFa: 'کرمانشاه، کلوچه‌ش هنوز همون قیمت قدیمه!' },
  { slug: 'urmia', nameFa: 'ارومیه', province: 'azgharbi', sloganFa: 'ارومیه، سیبش ترشه، حدس‌هات نه!' },
  { slug: 'rasht', nameFa: 'رشت', province: 'gilan', sloganFa: 'رشت، باران می‌بارد و قیمت‌ها هم!' },
  { slug: 'zahedan', nameFa: 'زاهدان', province: 'sistan', sloganFa: 'زاهدان، دور از چشم، نزدیک به دل!' },
  { slug: 'hamadan', nameFa: 'همدان', province: 'hamadan', sloganFa: 'همدان، شهری که از قیمتِ دیروز هم قدیمی‌تره!' },
  { slug: 'kerman', nameFa: 'کرمان', province: 'kerman', sloganFa: 'کرمان، پسته می‌شکنیم، رکورد هم می‌شکنیم!' },
  { slug: 'yazd', nameFa: 'یزد', province: 'yazd', sloganFa: 'یزد، آروم و بادگیر، ولی تو بازی تند!' },
  { slug: 'ardabil', nameFa: 'اردبیل', province: 'ardabil', sloganFa: 'اردبیل، سرمای سبلان، دل گرم به بردِ بعدی!' },
  { slug: 'bandar-abbas', nameFa: 'بندرعباس', province: 'hormozgan', sloganFa: 'بندرعباس، دریا و دلار، هر دو موج دارن!' },
  { slug: 'arak', nameFa: 'اراک', province: 'markazi', sloganFa: 'اراک، سنگین و محکم، مثل حدس‌های درست!' },
  { slug: 'zanjan', nameFa: 'زنجان', province: 'zanjan', sloganFa: 'زنجان، چاقوش تیزه، حدس‌هاش تیزتر!' },
  { slug: 'sanandaj', nameFa: 'سنندج', province: 'kurdistan', sloganFa: 'سنندج، با دف و دل، حریف همه‌ایم!' },
  { slug: 'qazvin', nameFa: 'قزوین', province: 'qazvin', sloganFa: 'قزوین، قدیمی‌ترین شهرِ دوزاری‌های خوب!' },
  { slug: 'khorramabad', nameFa: 'خرم‌آباد', province: 'lorestan', sloganFa: 'خرم‌آباد، از فلک‌الافلاک تا صدر جدول!' },
  { slug: 'gorgan', nameFa: 'گرگان', province: 'golestan', sloganFa: 'گرگان، سبز و سخت‌جون تا آخر بازی!' },
  { slug: 'sari', nameFa: 'ساری', province: 'mazandaran', sloganFa: 'ساری، برنجش دونه‌دونه، بردش هم!' },
  { slug: 'bushehr', nameFa: 'بوشهر', province: 'bushehr', sloganFa: 'بوشهر، بوی دریا و بوی برد!' },
  { slug: 'birjand', nameFa: 'بیرجند', province: 'khjonubi', sloganFa: 'بیرجند، زعفرون و عناب؛ حدس‌هامون عیار!' },
  { slug: 'bojnord', nameFa: 'بجنورد', province: 'khshomali', sloganFa: 'بجنورد، کوه‌نشین‌ها دست بالا رو دارن!' },
  { slug: 'semnan', nameFa: 'سمنان', province: 'semnan', sloganFa: 'سمنان، کویرِ آروم، ضربه‌ی ناگهانی!' },
  { slug: 'ilam', nameFa: 'ایلام', province: 'ilam', sloganFa: 'ایلام، از کبیرکوه تا قله‌ی جدول!' },
  { slug: 'yasuj', nameFa: 'یاسوج', province: 'kohgiluyeh', sloganFa: 'یاسوج، کوه‌پایه‌ایم، قله رو می‌گیریم!' },
  { slug: 'shahrekord', nameFa: 'شهرکرد', province: 'chaharmahal', sloganFa: 'شهرکرد، چهارمحال و هزار حدس درست!' },
  { slug: 'abadan', nameFa: 'آبادان', province: 'khuzestan', sloganFa: 'آبادان، فلافل و نخل، یادش بخیر!' },
  { slug: 'dezful', nameFa: 'دزفول', province: 'khuzestan', sloganFa: 'دزفول، پل قدیمی، قیمتای قدیمی‌تر!' },
  { slug: 'kish', nameFa: 'کیش', province: 'hormozgan', sloganFa: 'کیش، جزیره‌ی بی‌خیال، حدس‌های جدی!' },
  { slug: 'other', nameFa: 'شهر دیگر', province: null, sloganFa: 'هر شهری باشی، دوزاری مال همه‌ست!' },
  { slug: 'istanbul', nameFa: 'استانبول', province: 'istanbul', sloganFa: 'استانبول، از غربت تا قیمتِ نوستالژی!' },
  { slug: 'dubai', nameFa: 'دبی', province: 'dubai', sloganFa: 'دبی، دور از خونه، نزدیک به قیمتای خونه!' },
  { slug: 'toronto', nameFa: 'تورنتو', province: 'toronto', sloganFa: 'تورنتو، برف و دل‌تنگی، حدس‌ها گرم!' },
  { slug: 'los-angeles', nameFa: 'لس‌آنجلس', province: 'la', sloganFa: 'لس‌آنجلس، شهر فرشته‌ها و ایرونی‌های دل‌تنگ!' },
  { slug: 'london', nameFa: 'لندن', province: 'london', sloganFa: 'لندن، مه و مهمونی، دلِ ایرونی همیشه تهرونه!' },
  { slug: 'paris', nameFa: 'پاریس', province: 'paris', sloganFa: 'پاریس، یه نون تازه، یه یاد قدیمی!' },
  { slug: 'berlin', nameFa: 'برلین', province: 'berlin', sloganFa: 'برلین، دور از وطن، نزدیک به خاطره‌ها!' },
  { slug: 'abroad-other', nameFa: 'کشور دیگر', province: 'abroad', sloganFa: 'هر جای دنیا باشی، دوزاری ایرونیه!' },
];
