/** Starting list of cities; the admin panel can add, rename and hide cities (table `cities`). Slugs are stable keys. */
export const DEFAULT_CITIES: readonly { slug: string; nameFa: string }[] = [
  { slug: 'tehran', nameFa: 'تهران' },
  { slug: 'mashhad', nameFa: 'مشهد' },
  { slug: 'isfahan', nameFa: 'اصفهان' },
  { slug: 'karaj', nameFa: 'کرج' },
  { slug: 'shiraz', nameFa: 'شیراز' },
  { slug: 'tabriz', nameFa: 'تبریز' },
  { slug: 'qom', nameFa: 'قم' },
  { slug: 'ahvaz', nameFa: 'اهواز' },
  { slug: 'kermanshah', nameFa: 'کرمانشاه' },
  { slug: 'urmia', nameFa: 'ارومیه' },
  { slug: 'rasht', nameFa: 'رشت' },
  { slug: 'zahedan', nameFa: 'زاهدان' },
  { slug: 'hamadan', nameFa: 'همدان' },
  { slug: 'kerman', nameFa: 'کرمان' },
  { slug: 'yazd', nameFa: 'یزد' },
  { slug: 'ardabil', nameFa: 'اردبیل' },
  { slug: 'bandar-abbas', nameFa: 'بندرعباس' },
  { slug: 'arak', nameFa: 'اراک' },
  { slug: 'zanjan', nameFa: 'زنجان' },
  { slug: 'sanandaj', nameFa: 'سنندج' },
  { slug: 'qazvin', nameFa: 'قزوین' },
  { slug: 'khorramabad', nameFa: 'خرم‌آباد' },
  { slug: 'gorgan', nameFa: 'گرگان' },
  { slug: 'sari', nameFa: 'ساری' },
  { slug: 'bushehr', nameFa: 'بوشهر' },
  { slug: 'birjand', nameFa: 'بیرجند' },
  { slug: 'bojnord', nameFa: 'بجنورد' },
  { slug: 'semnan', nameFa: 'سمنان' },
  { slug: 'ilam', nameFa: 'ایلام' },
  { slug: 'yasuj', nameFa: 'یاسوج' },
  { slug: 'shahrekord', nameFa: 'شهرکرد' },
  { slug: 'abadan', nameFa: 'آبادان' },
  { slug: 'dezful', nameFa: 'دزفول' },
  { slug: 'kish', nameFa: 'کیش' },
  { slug: 'other', nameFa: 'شهر دیگر' },
];
