// GENERATED by apps/mobile/scripts/build-wear.mjs from assets/wear/**/*.svg: do not edit.
import type { CosmeticSlot } from './hints-contract.js';

/** Wearables drawn as SVG files (key -> slot); merged over the built-in table in wear.ts. */
export const GENERATED_WEAR_SLOT_OF: Readonly<Record<string, CosmeticSlot>> = {
};
