// GENERATED by apps/mobile/scripts/build-wear.mjs from assets/wear/**/*.svg: do not edit.
import type { CosmeticSlot } from './hints-contract.js';

/** Wearables drawn as SVG files (key -> slot); merged over the built-in table in wear.ts. */
export const GENERATED_WEAR_SLOT_OF: Readonly<Record<string, CosmeticSlot>> = {
  bowtie: 'accessory',
  cape: 'accessory',
  medal: 'accessory',
  necklace: 'accessory',
  glassesHeart: 'glasses',
  glassesNerd: 'glasses',
  glassesStar: 'glasses',
  monocle: 'glasses',
  hairAfro: 'hair',
  hairBob: 'hair',
  hairMohawk: 'hair',
  hairPonytail: 'hair',
  hairSpiky: 'hair',
  bandana: 'hat',
  cap: 'hat',
  chef: 'hat',
  cowboy: 'hat',
  fez: 'hat',
  partyHat: 'hat',
  topHat: 'hat',
  wizard: 'hat',
  apron: 'outfit',
  ghaba: 'outfit',
  hoodie: 'outfit',
  sportShirt: 'outfit',
  suit: 'outfit',
  tshirt: 'outfit',
};
