// GENERATED by scripts/build-wear.mjs from assets/wear/**/*.svg: do not edit.
import type { ReactElement } from 'react';
import { Circle, G, Path, Rect } from 'react-native-svg';

export interface GeneratedWear {
  front?: () => ReactElement;
  back?: () => ReactElement;
}

export const GENERATED_WEAR: Readonly<Record<string, GeneratedWear>> = {
  bowtie: {
    front: () => (
      <G>
        <Path d="M100 152L80 140L80 164Z" fill="#D93B3B" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
        <Path d="M100 152L120 140L120 164Z" fill="#D93B3B" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
        <Rect x="94" y="145" width="12" height="14" rx="3" fill="#B52424" stroke="#3A2418" strokeWidth="2.2" />
      </G>
    ),
  },
  cape: {
    front: () => (
      <G>
        <Path d="M68 148Q100 164 132 148L130 156Q100 172 70 156Z" fill="#C2272D" stroke="#3A2418" strokeWidth="2.8" strokeLinejoin="round" />
        <Circle cx="100" cy="164" r="5" fill="#FFC93C" stroke="#3A2418" strokeWidth="2.2" />
      </G>
    ),
    back: () => (
      <G>
        <Path d="M66 148L36 238Q100 256 164 238L134 148Z" fill="#C2272D" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M74 170L58 232M126 170L142 232" fill="none" stroke="#fff" strokeWidth="2.4" strokeLinecap="round" opacity="0.35" />
      </G>
    ),
  },
  medal: {
    front: () => (
      <G>
        <Path d="M84 141L101 166L95 174L78 146Z" fill="#D93B3B" stroke="#3A2418" strokeWidth="2.4" strokeLinejoin="round" />
        <Path d="M116 141L99 166L105 174L122 146Z" fill="#3F72D0" stroke="#3A2418" strokeWidth="2.4" strokeLinejoin="round" />
        <Circle cx="100" cy="182" r="12" fill="#FFC93C" stroke="#3A2418" strokeWidth="2.8" />
        <Circle cx="100" cy="182" r="7.2" fill="none" stroke="#C48A0E" strokeWidth="2" />
        <Path d="M100.0 177.0L101.3 180.2L104.8 180.5L102.1 182.7L102.9 186.0L100.0 184.2L97.1 186.0L97.9 182.7L95.2 180.5L98.7 180.2Z" fill="#C48A0E" stroke="#3A2418" strokeWidth="1" strokeLinejoin="round" />
      </G>
    ),
  },
  necklace: {
    front: () => (
      <G>
        <Path d="M74 146Q100 188 126 146" fill="none" stroke="#C48A0E" strokeWidth="3.4" strokeLinecap="round" />
        <Path d="M74 146Q100 188 126 146" fill="none" stroke="#FFE48A" strokeWidth="1.6" strokeLinecap="round" />
        <Circle cx="100" cy="170" r="7" fill="#FFC93C" stroke="#3A2418" strokeWidth="2.4" />
        <Circle cx="100" cy="170" r="3.2" fill="#3FC1F0" stroke="#3A2418" strokeWidth="1.6" />
      </G>
    ),
  },
  glassesHeart: {
    front: () => (
      <G>
        <Path d="M88 87C73 79 71 66 79.5 63C84 61.5 88 65 88 68C88 65 92 61.5 96.5 63C105 66 103 79 88 87Z" fill="#FF4D8D" stroke="#3A2418" strokeWidth="2.8" strokeLinejoin="round" fillOpacity="0.9" />
        <G transform="translate(24 0)">
          <Path d="M88 87C73 79 71 66 79.5 63C84 61.5 88 65 88 68C88 65 92 61.5 96.5 63C105 66 103 79 88 87Z" fill="#FF4D8D" stroke="#3A2418" strokeWidth="2.8" strokeLinejoin="round" fillOpacity="0.9" />
        </G>
        <Path d="M103 70Q100 67 97 70M76 70L62 66M124 70L138 66" fill="none" stroke="#3A2418" strokeWidth="3" strokeLinecap="round" />
        <Path d="M80 68Q82 66 85 66" fill="none" stroke="#fff" strokeWidth="2" strokeLinecap="round" opacity="0.8" />
      </G>
    ),
  },
  glassesNerd: {
    front: () => (
      <G>
        <Rect x="71" y="61" width="29" height="25" rx="7" fill="#fff" fillOpacity="0.16" stroke="#1E2A4A" strokeWidth="3.6" />
        <Rect x="100" y="61" width="29" height="25" rx="7" fill="#fff" fillOpacity="0.16" stroke="#1E2A4A" strokeWidth="3.6" />
        <Path d="M100 70L100 70M71 68L62 66M129 68L138 66" fill="none" stroke="#1E2A4A" strokeWidth="3.6" strokeLinecap="round" />
        <Path d="M77 67Q80 65 85 65" fill="none" stroke="#fff" strokeWidth="2.2" strokeLinecap="round" opacity="0.8" />
        <Path d="M96 66L104 66" fill="none" stroke="#1E2A4A" strokeWidth="3.6" strokeLinecap="round" />
      </G>
    ),
  },
  glassesStar: {
    front: () => (
      <G>
        <Path d="M88.0 57.0L92.7 67.5L104.2 68.7L95.6 76.5L98.0 87.8L88.0 82.0L78.0 87.8L80.4 76.5L71.8 68.7L83.3 67.5Z" fill="#FFC93C" stroke="#3A2418" strokeWidth="2.8" strokeLinejoin="round" fillOpacity="0.92" />
        <Path d="M112.0 57.0L116.7 67.5L128.2 68.7L119.6 76.5L122.0 87.8L112.0 82.0L102.0 87.8L104.4 76.5L95.8 68.7L107.3 67.5Z" fill="#FFC93C" stroke="#3A2418" strokeWidth="2.8" strokeLinejoin="round" fillOpacity="0.92" />
        <Path d="M101 72Q100 70 99 72M72 70L62 68M128 70L138 68" fill="none" stroke="#3A2418" strokeWidth="3" strokeLinecap="round" />
      </G>
    ),
  },
  monocle: {
    front: () => (
      <G>
        <Circle cx="112" cy="74" r="16" fill="#fff" fillOpacity="0.16" stroke="#C48A0E" strokeWidth="3.6" />
        <Circle cx="112" cy="74" r="16" fill="none" stroke="#3A2418" strokeWidth="1.4" />
        <Path d="M128 80Q140 110 132 150" fill="none" stroke="#C48A0E" strokeWidth="2.4" strokeLinecap="round" />
        <Path d="M103 66q3-3 7-3" fill="none" stroke="#fff" strokeWidth="2.2" strokeLinecap="round" />
      </G>
    ),
  },
  hairAfro: {
    front: () => (
      <G>
        <Path d="M62 66C56 36 78 12 100 12C122 12 144 36 138 66C128 54 114 50 100 54C86 50 72 54 62 66Z" fill="#2A1A12" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
      </G>
    ),
    back: () => (
      <G>
        <Path d="M44 50C38 16 70 -4 100 -4C130 -4 162 16 156 50C166 76 152 102 132 102L68 102C48 102 34 76 44 50Z" fill="#2A1A12" stroke="#3A2418" strokeWidth="2.8" strokeLinejoin="round" />
      </G>
    ),
  },
  hairBob: {
    front: () => (
      <G>
        <Path d="M62 66C56 36 78 12 100 12C122 12 144 36 138 66C128 54 114 50 100 54C86 50 72 54 62 66Z" fill="#8A3A1E" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
        <Path d="M62 66C54 94 58 122 68 138L80 133C73 114 73 92 79 72Z" fill="#8A3A1E" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
        <Path d="M138 66C146 94 142 122 132 138L120 133C127 114 127 92 121 72Z" fill="#8A3A1E" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
        <Path d="M78 30Q88 22 98 22" fill="none" stroke="#fff" strokeWidth="2" strokeLinecap="round" opacity="0.4" />
      </G>
    ),
    back: () => (
      <G>
        <Path d="M54 64C48 104 56 134 70 146Q100 154 130 146C144 134 152 104 146 64C142 22 58 22 54 64Z" fill="#8A3A1E" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
      </G>
    ),
  },
  hairMohawk: {
    front: () => (
      <G>
        <Path d="M62 66C56 36 78 12 100 12C122 12 144 36 138 66C128 54 114 50 100 54C86 50 72 54 62 66Z" fill="#2A1A12" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" fillOpacity="0.28" />
        <Path d="M88 52L88 14L95 30L100 -4L105 30L112 14L112 52Q100 44 88 52Z" fill="#E04A8A" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
      </G>
    ),
  },
  hairPonytail: {
    front: () => (
      <G>
        <Path d="M62 66C56 36 78 12 100 12C122 12 144 36 138 66C128 54 114 50 100 54C86 50 72 54 62 66Z" fill="#2A1A12" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
        <Circle cx="139" cy="46" r="4.2" fill="#FF4D8D" stroke="#3A2418" strokeWidth="2" />
        <Path d="M80 30Q88 22 98 22" fill="none" stroke="#fff" strokeWidth="2" strokeLinecap="round" opacity="0.35" />
      </G>
    ),
    back: () => (
      <G>
        <Path d="M138 44C170 32 182 68 162 102C160 84 154 72 140 62Z" fill="#2A1A12" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
      </G>
    ),
  },
  hairSpiky: {
    front: () => (
      <G>
        <Path d="M62 66C56 40 64 26 72 26L72 8L86 22L94 2L102 20L112 2L116 22L130 8L130 26C138 28 144 44 138 66C128 54 114 50 100 54C86 50 72 54 62 66Z" fill="#2A1A12" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
        <Path d="M80 36Q88 30 96 30" fill="none" stroke="#fff" strokeWidth="2" strokeLinecap="round" opacity="0.35" />
      </G>
    ),
  },
  bandana: {
    front: () => (
      <G>
        <Path d="M62 68C56 36 78 14 100 14C122 14 144 36 138 68Q100 50 62 68Z" fill="#D93B3B" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M136 56L158 46L152 64L160 74L138 68Z" fill="#D93B3B" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
        <Circle cx="76" cy="52" r="2.8" fill="#fff" />
        <Circle cx="90" cy="34" r="2.8" fill="#fff" />
        <Circle cx="108" cy="28" r="2.8" fill="#fff" />
        <Circle cx="124" cy="40" r="2.8" fill="#fff" />
        <Circle cx="100" cy="48" r="2.8" fill="#fff" />
        <Path d="M66 62Q100 46 134 62" fill="none" stroke="#B52424" strokeWidth="2.4" strokeLinecap="round" />
      </G>
    ),
  },
  cap: {
    front: () => (
      <G>
        <Path d="M66 54C62 16 138 16 134 54Z" fill="#3F72D0" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M98 52Q150 50 162 64Q130 66 98 60Z" fill="#2F58A8" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Circle cx="100" cy="21" r="4.4" fill="#2F58A8" stroke="#3A2418" strokeWidth="2.2" />
        <Path d="M78 30Q88 22 98 22" fill="none" stroke="#fff" strokeWidth="2.4" strokeLinecap="round" opacity="0.55" />
        <Path d="M100 22L100 52" fill="none" stroke="#2F58A8" strokeWidth="2" strokeLinecap="round" opacity="0.6" />
      </G>
    ),
  },
  chef: {
    front: () => (
      <G>
        <Path d="M70 52L70 42Q54 38 58 24Q64 10 82 16Q90 0 106 8Q122 2 132 16Q148 18 144 34Q142 42 130 42L130 52Z" fill="#FFFFFF" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M70 42L130 42L130 52Q100 58 70 52Z" fill="#EFEFEF" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
        <Path d="M86 38L88 20M104 38L104 16M120 38L118 20" fill="none" stroke="#CFC9D6" strokeWidth="2.2" strokeLinecap="round" />
      </G>
    ),
  },
  cowboy: {
    front: () => (
      <G>
        <Path d="M38 54Q58 38 78 46Q100 40 122 46Q142 38 162 54Q150 70 100 64Q50 70 38 54Z" fill="#A0642E" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M72 50Q70 14 90 20Q100 14 110 20Q130 14 128 50Q100 42 72 50Z" fill="#B97A3C" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M72 44Q100 52 128 44L128 50Q100 58 72 50Z" fill="#5A3A2A" stroke="#3A2418" strokeWidth="2.4" strokeLinejoin="round" />
        <Path d="M48 54Q58 52 70 52" fill="none" stroke="#fff" strokeWidth="2" strokeLinecap="round" opacity="0.4" />
      </G>
    ),
  },
  fez: {
    front: () => (
      <G>
        <Path d="M72 52L80 18Q100 10 120 18L128 52Q100 58 72 52Z" fill="#C9362E" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M100 14Q122 8 128 28" fill="none" stroke="#FFC93C" strokeWidth="3" strokeLinecap="round" />
        <Circle cx="128" cy="32" r="4.4" fill="#FFC93C" stroke="#3A2418" strokeWidth="2.2" />
        <Path d="M82 30Q96 24 108 24" fill="none" stroke="#fff" strokeWidth="2.2" strokeLinecap="round" opacity="0.45" />
      </G>
    ),
  },
  partyHat: {
    front: () => (
      <G>
        <Path d="M76 50L100 -6L124 50Q100 58 76 50Z" fill="#FF4D8D" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M84 36L116 30M80 44L120 38M90 22L110 18" fill="none" stroke="#fff" strokeWidth="3" strokeLinecap="round" opacity="0.85" />
        <Circle cx="100" cy="-8" r="7" fill="#FFC93C" stroke="#3A2418" strokeWidth="2.4" />
      </G>
    ),
  },
  topHat: {
    front: () => (
      <G>
        <Path d="M72 46L76 6Q100 0 124 6L128 46Q100 54 72 46Z" fill="#2B2B3A" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M73.5 36Q100 44 126.5 36L128 46Q100 54 72 46Z" fill="#D93B3B" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
        <Path d="M54 50Q100 64 146 50Q146 42 100 42Q54 42 54 50Z" fill="#2B2B3A" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M82 14L84 30" fill="none" stroke="#fff" strokeWidth="2.4" strokeLinecap="round" opacity="0.4" />
      </G>
    ),
  },
  wizard: {
    front: () => (
      <G>
        <Path d="M66 52Q100 42 134 52L106 -12Q100 -16 96 -12Q92 14 66 52Z" fill="#4B3A9E" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M50 54Q100 70 150 54Q140 46 100 48Q60 46 50 54Z" fill="#4B3A9E" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M68 48Q100 58 132 48L130 54Q100 64 70 54Z" fill="#FFC93C" stroke="#3A2418" strokeWidth="2.4" strokeLinejoin="round" />
        <Path d="M94.0 14.0L96.0 19.2L101.6 19.5L97.2 23.1L98.7 28.5L94.0 25.4L89.3 28.5L90.8 23.1L86.4 19.5L92.0 19.2Z" fill="#FFC93C" stroke="#3A2418" strokeWidth="1.8" strokeLinejoin="round" />
        <Path d="M108.0 -7.0L109.3 -3.8L112.8 -3.5L110.1 -1.3L110.9 2.0L108.0 0.2L105.1 2.0L105.9 -1.3L103.2 -3.5L106.7 -3.8Z" fill="#FFC93C" stroke="#3A2418" strokeWidth="1.6" strokeLinejoin="round" />
      </G>
    ),
  },
  apron: {
    front: () => (
      <G>
        <Path d="M80 150L120 150L130 214Q100 224 70 214Z" fill="#F4E8D0" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M82 150L90 142M118 150L110 142" fill="none" stroke="#3A2418" strokeWidth="3" strokeLinecap="round" />
        <Rect x="88" y="184" width="24" height="18" rx="4" fill="#E9D7B3" stroke="#3A2418" strokeWidth="2.4" />
        <Path d="M76 170Q100 178 124 170" fill="none" stroke="#C9A56A" strokeWidth="2.4" strokeLinecap="round" opacity="0.8" />
      </G>
    ),
  },
  ghaba: {
    front: () => (
      <G>
        <Path d="M70 146C62 170 60 196 62 216Q100 226 138 216C140 196 138 170 130 146Q100 138 70 146Z" fill="#8E2A3A" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M100 142L100 218" fill="none" stroke="#FFC93C" strokeWidth="5" strokeLinecap="round" />
        <Path d="M70 158Q100 172 130 158" fill="none" stroke="#FFC93C" strokeWidth="3" strokeLinecap="round" opacity="0.9" />
        <Path d="M62 190Q100 204 138 190L139 204Q100 218 61 204Z" fill="#FFC93C" stroke="#3A2418" strokeWidth="2.8" strokeLinejoin="round" />
        <Circle cx="84" cy="176" r="2.6" fill="#FFC93C" stroke="#3A2418" strokeWidth="1.6" />
        <Circle cx="116" cy="176" r="2.6" fill="#FFC93C" stroke="#3A2418" strokeWidth="1.6" />
      </G>
    ),
  },
  hoodie: {
    front: () => (
      <G>
        <Path d="M70 146C62 170 60 196 62 216Q100 226 138 216C140 196 138 170 130 146Q100 138 70 146Z" fill="#5A5A6E" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M72 148Q100 170 128 148Q124 136 100 138Q76 136 72 148Z" fill="#464656" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
        <Path d="M78 192Q100 202 122 192L126 214Q100 220 74 214Z" fill="#4C4C5E" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
        <Path d="M92 156L90 178M108 156L110 178" fill="none" stroke="#fff" strokeWidth="2.6" strokeLinecap="round" opacity="0.85" />
      </G>
    ),
  },
  sportShirt: {
    front: () => (
      <G>
        <Path d="M70 146C62 170 60 196 62 216Q100 226 138 216C140 196 138 170 130 146Q100 138 70 146Z" fill="#E04A3A" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M86 142L100 156L114 142" fill="none" stroke="#fff" strokeWidth="4.4" strokeLinecap="round" />
        <Path d="M84 160L82 214M116 160L118 214" fill="none" stroke="#fff" strokeWidth="5" strokeLinecap="round" />
        <Circle cx="100" cy="188" r="9" fill="#fff" stroke="#3A2418" strokeWidth="2.2" />
        <Path d="M96 188L100 183L100 193" fill="none" stroke="#3A2418" strokeWidth="2.4" strokeLinecap="round" />
      </G>
    ),
  },
  suit: {
    front: () => (
      <G>
        <Path d="M70 146C62 170 60 196 62 216Q100 226 138 216C140 196 138 170 130 146Q100 138 70 146Z" fill="#2E3A5A" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M86 143L100 178L114 143Q100 150 86 143Z" fill="#FFFFFF" stroke="#3A2418" strokeWidth="2.6" strokeLinejoin="round" />
        <Path d="M97 150L103 150L106 178L100 190L94 178Z" fill="#D93B3B" stroke="#3A2418" strokeWidth="2.4" strokeLinejoin="round" />
        <Path d="M86 143L82 176M114 143L118 176" fill="none" stroke="#3A2418" strokeWidth="2.4" strokeLinecap="round" />
        <Circle cx="112" cy="196" r="2.4" fill="#FFC93C" stroke="#3A2418" strokeWidth="1.6" />
        <Circle cx="112" cy="206" r="2.4" fill="#FFC93C" stroke="#3A2418" strokeWidth="1.6" />
      </G>
    ),
  },
  tshirt: {
    front: () => (
      <G>
        <Path d="M70 146C62 170 60 196 62 216Q100 226 138 216C140 196 138 170 130 146Q100 138 70 146Z" fill="#1F9BD6" stroke="#3A2418" strokeWidth="3" strokeLinejoin="round" />
        <Path d="M84 143Q100 160 116 143Q100 150 84 143Z" fill="#157BAA" stroke="#3A2418" strokeWidth="2.4" strokeLinejoin="round" />
        <Circle cx="100" cy="184" r="13" fill="#FFC93C" stroke="#3A2418" strokeWidth="2.6" />
        <Circle cx="100" cy="184" r="8.4" fill="none" stroke="#C48A0E" strokeWidth="2" />
      </G>
    ),
  },
};
