// GENERATED by scripts/build-wear.mjs from assets/wear/**/*.svg: do not edit.
import type { ReactElement } from 'react';

export interface GeneratedWear {
  front?: () => ReactElement;
  back?: () => ReactElement;
}

export const GENERATED_WEAR: Readonly<Record<string, GeneratedWear>> = {
};
