CREATE TABLE `ai_schedules` (
	`id` char(36) NOT NULL,
	`name` varchar(80) NOT NULL,
	`kind` varchar(20) NOT NULL,
	`enabled` boolean NOT NULL DEFAULT true,
	`cron` varchar(60) NOT NULL,
	`provider` varchar(20) NOT NULL,
	`model` varchar(80) NOT NULL DEFAULT '',
	`hint` varchar(300) NOT NULL DEFAULT '',
	`count` int NOT NULL DEFAULT 1,
	`age_track` varchar(8) NOT NULL DEFAULT 'adult',
	`style` varchar(8) NOT NULL DEFAULT 'witty',
	`category` varchar(40),
	`from_year` int,
	`to_year` int,
	`topic` varchar(300) NOT NULL DEFAULT '',
	`length` varchar(8) NOT NULL DEFAULT 'medium',
	`tone` varchar(16) NOT NULL DEFAULT 'friendly',
	`next_run_at` datetime(3),
	`last_run_at` datetime(3),
	`last_status` varchar(8),
	`last_message` varchar(300) NOT NULL DEFAULT '',
	`last_saved` int NOT NULL DEFAULT 0,
	`created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	CONSTRAINT `ai_schedules_id` PRIMARY KEY(`id`)
);
